# This config should be kept as similar as possible to the one at
# cluster/addons/gci/fluentd-gcp.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat-logging
  namespace: kube-system
  labels:
    k8s-app: filebeat-logging
    version: v1
    #kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      name: filebeat-logging
      namespace: kube-system
      labels:
        k8s-app: filebeat-logging
    spec:
      dnsPolicy: Default
      containers:
      - name: filebeat-logging
        image: exabeat
        imagePullPolicy: Never
        volumeMounts:
        - name: varlog
          mountPath: /var/log/
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers