# This config should be kept as similar as possible to the one at
# cluster/addons/gci/fluentd-gcp.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-logging
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    #kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      name: fluentd-logging
      namespace: kube-system
      labels:
        k8s-app: fluentd-logging
    spec:
      dnsPolicy: Default
      containers:
      - name: fluentd-logging
        # For Production use replace image name by an image in your private registry and set imagePullPolicy to reasonable value.
        image: kubernetes-logging:1.19
        imagePullPolicy: Never
        volumeMounts:
        - name: varlog
          mountPath: /var/log/
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: fluentdposfiles
          mountPath: /var/lib/fluentd
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentdposfiles
        hostPath:
          path: /tmp/fluentd