---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: structured-logging
spec:
  revisionHistoryLimit: 3
  replicas: 3
  selector:
    matchLabels:
      app: structured-logging
      logformat: structured
  template:
    metadata:
      labels:
        app: structured-logging
        logformat: structured
    spec:
      containers:
      - name: logging-app
        image: local/loggingapp:0.1
        imagePullPolicy: Never
        args:
          - app
          - -structured
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
